"""init emotion_records table

Revision ID: 677dadaf8bc9
Revises: 
Create Date: 2026-02-25 16:34:10.805933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677dadaf8bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('emotion', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotion_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotion_records_request_id'), ['request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotion_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotion_records_request_id'))

    op.drop_table('emotion_records')
    # ### end Alembic commands ###
